export const FETCH_FILTERED_RECORDS_REQUEST = 'FETCH_FILTERED_RECORDS_REQUEST';
export const FETCH_FILTERED_RECORDS_SUCCESS = 'FETCH_FILTERED_RECORDS_SUCCESS';
export const FETCH_FILTERED_RECORDS_FAILURE = 'FETCH_FILTERED_RECORDS_FAILURE';
